// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chunk is the predicate function for chunk builders.
type Chunk func(*sql.Selector)

// Embedding is the predicate function for embedding builders.
type Embedding func(*sql.Selector)
