// Code generated by ent, DO NOT EDIT.

package chunk

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/TaiwoDevOps/jira-rag/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldID, id))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldPath, v))
}

// Nchunk applies equality check predicate on the "nchunk" field. It's identical to NchunkEQ.
func Nchunk(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldNchunk, v))
}

// Data applies equality check predicate on the "data" field. It's identical to DataEQ.
func Data(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldData, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldPath, v))
}

// NchunkEQ applies the EQ predicate on the "nchunk" field.
func NchunkEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldNchunk, v))
}

// NchunkNEQ applies the NEQ predicate on the "nchunk" field.
func NchunkNEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldNchunk, v))
}

// NchunkIn applies the In predicate on the "nchunk" field.
func NchunkIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldNchunk, vs...))
}

// NchunkNotIn applies the NotIn predicate on the "nchunk" field.
func NchunkNotIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldNchunk, vs...))
}

// NchunkGT applies the GT predicate on the "nchunk" field.
func NchunkGT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldNchunk, v))
}

// NchunkGTE applies the GTE predicate on the "nchunk" field.
func NchunkGTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldNchunk, v))
}

// NchunkLT applies the LT predicate on the "nchunk" field.
func NchunkLT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldNchunk, v))
}

// NchunkLTE applies the LTE predicate on the "nchunk" field.
func NchunkLTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldNchunk, v))
}

// DataEQ applies the EQ predicate on the "data" field.
func DataEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldData, v))
}

// DataNEQ applies the NEQ predicate on the "data" field.
func DataNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldData, v))
}

// DataIn applies the In predicate on the "data" field.
func DataIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldData, vs...))
}

// DataNotIn applies the NotIn predicate on the "data" field.
func DataNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldData, vs...))
}

// DataGT applies the GT predicate on the "data" field.
func DataGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldData, v))
}

// DataGTE applies the GTE predicate on the "data" field.
func DataGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldData, v))
}

// DataLT applies the LT predicate on the "data" field.
func DataLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldData, v))
}

// DataLTE applies the LTE predicate on the "data" field.
func DataLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldData, v))
}

// DataContains applies the Contains predicate on the "data" field.
func DataContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldData, v))
}

// DataHasPrefix applies the HasPrefix predicate on the "data" field.
func DataHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldData, v))
}

// DataHasSuffix applies the HasSuffix predicate on the "data" field.
func DataHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldData, v))
}

// DataEqualFold applies the EqualFold predicate on the "data" field.
func DataEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldData, v))
}

// DataContainsFold applies the ContainsFold predicate on the "data" field.
func DataContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldData, v))
}

// HasEmbedding applies the HasEdge predicate on the "embedding" edge.
func HasEmbedding() predicate.Chunk {
	return predicate.Chunk(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, EmbeddingTable, EmbeddingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmbeddingWith applies the HasEdge predicate on the "embedding" edge with a given conditions (other predicates).
func HasEmbeddingWith(preds ...predicate.Embedding) predicate.Chunk {
	return predicate.Chunk(func(s *sql.Selector) {
		step := newEmbeddingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.NotPredicates(p))
}
