// Code generated by ent, DO NOT EDIT.

package embedding

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/TaiwoDevOps/jira-rag/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Embedding {
	return predicate.Embedding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Embedding {
	return predicate.Embedding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Embedding {
	return predicate.Embedding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Embedding {
	return predicate.Embedding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Embedding {
	return predicate.Embedding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Embedding {
	return predicate.Embedding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Embedding {
	return predicate.Embedding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Embedding {
	return predicate.Embedding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Embedding {
	return predicate.Embedding(sql.FieldLTE(FieldID, id))
}

// Embedding applies equality check predicate on the "embedding" field. It's identical to EmbeddingEQ.
func Embedding(v pgvector.Vector) predicate.Embedding {
	return predicate.Embedding(sql.FieldEQ(FieldEmbedding, v))
}

// EmbeddingEQ applies the EQ predicate on the "embedding" field.
func EmbeddingEQ(v pgvector.Vector) predicate.Embedding {
	return predicate.Embedding(sql.FieldEQ(FieldEmbedding, v))
}

// EmbeddingNEQ applies the NEQ predicate on the "embedding" field.
func EmbeddingNEQ(v pgvector.Vector) predicate.Embedding {
	return predicate.Embedding(sql.FieldNEQ(FieldEmbedding, v))
}

// EmbeddingIn applies the In predicate on the "embedding" field.
func EmbeddingIn(vs ...pgvector.Vector) predicate.Embedding {
	return predicate.Embedding(sql.FieldIn(FieldEmbedding, vs...))
}

// EmbeddingNotIn applies the NotIn predicate on the "embedding" field.
func EmbeddingNotIn(vs ...pgvector.Vector) predicate.Embedding {
	return predicate.Embedding(sql.FieldNotIn(FieldEmbedding, vs...))
}

// EmbeddingGT applies the GT predicate on the "embedding" field.
func EmbeddingGT(v pgvector.Vector) predicate.Embedding {
	return predicate.Embedding(sql.FieldGT(FieldEmbedding, v))
}

// EmbeddingGTE applies the GTE predicate on the "embedding" field.
func EmbeddingGTE(v pgvector.Vector) predicate.Embedding {
	return predicate.Embedding(sql.FieldGTE(FieldEmbedding, v))
}

// EmbeddingLT applies the LT predicate on the "embedding" field.
func EmbeddingLT(v pgvector.Vector) predicate.Embedding {
	return predicate.Embedding(sql.FieldLT(FieldEmbedding, v))
}

// EmbeddingLTE applies the LTE predicate on the "embedding" field.
func EmbeddingLTE(v pgvector.Vector) predicate.Embedding {
	return predicate.Embedding(sql.FieldLTE(FieldEmbedding, v))
}

// HasChunk applies the HasEdge predicate on the "chunk" edge.
func HasChunk() predicate.Embedding {
	return predicate.Embedding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ChunkTable, ChunkColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChunkWith applies the HasEdge predicate on the "chunk" edge with a given conditions (other predicates).
func HasChunkWith(preds ...predicate.Chunk) predicate.Embedding {
	return predicate.Embedding(func(s *sql.Selector) {
		step := newChunkStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Embedding) predicate.Embedding {
	return predicate.Embedding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Embedding) predicate.Embedding {
	return predicate.Embedding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Embedding) predicate.Embedding {
	return predicate.Embedding(sql.NotPredicates(p))
}
