// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TaiwoDevOps/jira-rag/ent/chunk"
	"github.com/TaiwoDevOps/jira-rag/ent/embedding"
	"github.com/TaiwoDevOps/jira-rag/ent/predicate"
)

// ChunkUpdate is the builder for updating Chunk entities.
type ChunkUpdate struct {
	config
	hooks    []Hook
	mutation *ChunkMutation
}

// Where appends a list predicates to the ChunkUpdate builder.
func (cu *ChunkUpdate) Where(ps ...predicate.Chunk) *ChunkUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetPath sets the "path" field.
func (cu *ChunkUpdate) SetPath(s string) *ChunkUpdate {
	cu.mutation.SetPath(s)
	return cu
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (cu *ChunkUpdate) SetNillablePath(s *string) *ChunkUpdate {
	if s != nil {
		cu.SetPath(*s)
	}
	return cu
}

// SetNchunk sets the "nchunk" field.
func (cu *ChunkUpdate) SetNchunk(i int) *ChunkUpdate {
	cu.mutation.ResetNchunk()
	cu.mutation.SetNchunk(i)
	return cu
}

// SetNillableNchunk sets the "nchunk" field if the given value is not nil.
func (cu *ChunkUpdate) SetNillableNchunk(i *int) *ChunkUpdate {
	if i != nil {
		cu.SetNchunk(*i)
	}
	return cu
}

// AddNchunk adds i to the "nchunk" field.
func (cu *ChunkUpdate) AddNchunk(i int) *ChunkUpdate {
	cu.mutation.AddNchunk(i)
	return cu
}

// SetData sets the "data" field.
func (cu *ChunkUpdate) SetData(s string) *ChunkUpdate {
	cu.mutation.SetData(s)
	return cu
}

// SetNillableData sets the "data" field if the given value is not nil.
func (cu *ChunkUpdate) SetNillableData(s *string) *ChunkUpdate {
	if s != nil {
		cu.SetData(*s)
	}
	return cu
}

// SetEmbeddingID sets the "embedding" edge to the Embedding entity by ID.
func (cu *ChunkUpdate) SetEmbeddingID(id int) *ChunkUpdate {
	cu.mutation.SetEmbeddingID(id)
	return cu
}

// SetNillableEmbeddingID sets the "embedding" edge to the Embedding entity by ID if the given value is not nil.
func (cu *ChunkUpdate) SetNillableEmbeddingID(id *int) *ChunkUpdate {
	if id != nil {
		cu = cu.SetEmbeddingID(*id)
	}
	return cu
}

// SetEmbedding sets the "embedding" edge to the Embedding entity.
func (cu *ChunkUpdate) SetEmbedding(e *Embedding) *ChunkUpdate {
	return cu.SetEmbeddingID(e.ID)
}

// Mutation returns the ChunkMutation object of the builder.
func (cu *ChunkUpdate) Mutation() *ChunkMutation {
	return cu.mutation
}

// ClearEmbedding clears the "embedding" edge to the Embedding entity.
func (cu *ChunkUpdate) ClearEmbedding() *ChunkUpdate {
	cu.mutation.ClearEmbedding()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChunkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChunkUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChunkUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChunkUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *ChunkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(chunk.Table, chunk.Columns, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Path(); ok {
		_spec.SetField(chunk.FieldPath, field.TypeString, value)
	}
	if value, ok := cu.mutation.Nchunk(); ok {
		_spec.SetField(chunk.FieldNchunk, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedNchunk(); ok {
		_spec.AddField(chunk.FieldNchunk, field.TypeInt, value)
	}
	if value, ok := cu.mutation.Data(); ok {
		_spec.SetField(chunk.FieldData, field.TypeString, value)
	}
	if cu.mutation.EmbeddingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chunk.EmbeddingTable,
			Columns: []string{chunk.EmbeddingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(embedding.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.EmbeddingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chunk.EmbeddingTable,
			Columns: []string{chunk.EmbeddingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(embedding.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChunkUpdateOne is the builder for updating a single Chunk entity.
type ChunkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChunkMutation
}

// SetPath sets the "path" field.
func (cuo *ChunkUpdateOne) SetPath(s string) *ChunkUpdateOne {
	cuo.mutation.SetPath(s)
	return cuo
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (cuo *ChunkUpdateOne) SetNillablePath(s *string) *ChunkUpdateOne {
	if s != nil {
		cuo.SetPath(*s)
	}
	return cuo
}

// SetNchunk sets the "nchunk" field.
func (cuo *ChunkUpdateOne) SetNchunk(i int) *ChunkUpdateOne {
	cuo.mutation.ResetNchunk()
	cuo.mutation.SetNchunk(i)
	return cuo
}

// SetNillableNchunk sets the "nchunk" field if the given value is not nil.
func (cuo *ChunkUpdateOne) SetNillableNchunk(i *int) *ChunkUpdateOne {
	if i != nil {
		cuo.SetNchunk(*i)
	}
	return cuo
}

// AddNchunk adds i to the "nchunk" field.
func (cuo *ChunkUpdateOne) AddNchunk(i int) *ChunkUpdateOne {
	cuo.mutation.AddNchunk(i)
	return cuo
}

// SetData sets the "data" field.
func (cuo *ChunkUpdateOne) SetData(s string) *ChunkUpdateOne {
	cuo.mutation.SetData(s)
	return cuo
}

// SetNillableData sets the "data" field if the given value is not nil.
func (cuo *ChunkUpdateOne) SetNillableData(s *string) *ChunkUpdateOne {
	if s != nil {
		cuo.SetData(*s)
	}
	return cuo
}

// SetEmbeddingID sets the "embedding" edge to the Embedding entity by ID.
func (cuo *ChunkUpdateOne) SetEmbeddingID(id int) *ChunkUpdateOne {
	cuo.mutation.SetEmbeddingID(id)
	return cuo
}

// SetNillableEmbeddingID sets the "embedding" edge to the Embedding entity by ID if the given value is not nil.
func (cuo *ChunkUpdateOne) SetNillableEmbeddingID(id *int) *ChunkUpdateOne {
	if id != nil {
		cuo = cuo.SetEmbeddingID(*id)
	}
	return cuo
}

// SetEmbedding sets the "embedding" edge to the Embedding entity.
func (cuo *ChunkUpdateOne) SetEmbedding(e *Embedding) *ChunkUpdateOne {
	return cuo.SetEmbeddingID(e.ID)
}

// Mutation returns the ChunkMutation object of the builder.
func (cuo *ChunkUpdateOne) Mutation() *ChunkMutation {
	return cuo.mutation
}

// ClearEmbedding clears the "embedding" edge to the Embedding entity.
func (cuo *ChunkUpdateOne) ClearEmbedding() *ChunkUpdateOne {
	cuo.mutation.ClearEmbedding()
	return cuo
}

// Where appends a list predicates to the ChunkUpdate builder.
func (cuo *ChunkUpdateOne) Where(ps ...predicate.Chunk) *ChunkUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChunkUpdateOne) Select(field string, fields ...string) *ChunkUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chunk entity.
func (cuo *ChunkUpdateOne) Save(ctx context.Context) (*Chunk, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChunkUpdateOne) SaveX(ctx context.Context) *Chunk {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChunkUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChunkUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *ChunkUpdateOne) sqlSave(ctx context.Context) (_node *Chunk, err error) {
	_spec := sqlgraph.NewUpdateSpec(chunk.Table, chunk.Columns, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chunk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chunk.FieldID)
		for _, f := range fields {
			if !chunk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Path(); ok {
		_spec.SetField(chunk.FieldPath, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Nchunk(); ok {
		_spec.SetField(chunk.FieldNchunk, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedNchunk(); ok {
		_spec.AddField(chunk.FieldNchunk, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.Data(); ok {
		_spec.SetField(chunk.FieldData, field.TypeString, value)
	}
	if cuo.mutation.EmbeddingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chunk.EmbeddingTable,
			Columns: []string{chunk.EmbeddingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(embedding.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.EmbeddingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chunk.EmbeddingTable,
			Columns: []string{chunk.EmbeddingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(embedding.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chunk{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
