// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TaiwoDevOps/jira-rag/ent/chunk"
	"github.com/TaiwoDevOps/jira-rag/ent/embedding"
	"github.com/TaiwoDevOps/jira-rag/ent/predicate"
)

// ChunkQuery is the builder for querying Chunk entities.
type ChunkQuery struct {
	config
	ctx           *QueryContext
	order         []chunk.OrderOption
	inters        []Interceptor
	predicates    []predicate.Chunk
	withEmbedding *EmbeddingQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChunkQuery builder.
func (cq *ChunkQuery) Where(ps ...predicate.Chunk) *ChunkQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *ChunkQuery) Limit(limit int) *ChunkQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *ChunkQuery) Offset(offset int) *ChunkQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *ChunkQuery) Unique(unique bool) *ChunkQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *ChunkQuery) Order(o ...chunk.OrderOption) *ChunkQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryEmbedding chains the current query on the "embedding" edge.
func (cq *ChunkQuery) QueryEmbedding() *EmbeddingQuery {
	query := (&EmbeddingClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chunk.Table, chunk.FieldID, selector),
			sqlgraph.To(embedding.Table, embedding.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, chunk.EmbeddingTable, chunk.EmbeddingColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Chunk entity from the query.
// Returns a *NotFoundError when no Chunk was found.
func (cq *ChunkQuery) First(ctx context.Context) (*Chunk, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chunk.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *ChunkQuery) FirstX(ctx context.Context) *Chunk {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Chunk ID from the query.
// Returns a *NotFoundError when no Chunk ID was found.
func (cq *ChunkQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chunk.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *ChunkQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Chunk entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Chunk entity is found.
// Returns a *NotFoundError when no Chunk entities are found.
func (cq *ChunkQuery) Only(ctx context.Context) (*Chunk, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chunk.Label}
	default:
		return nil, &NotSingularError{chunk.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *ChunkQuery) OnlyX(ctx context.Context) *Chunk {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Chunk ID in the query.
// Returns a *NotSingularError when more than one Chunk ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *ChunkQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chunk.Label}
	default:
		err = &NotSingularError{chunk.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *ChunkQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Chunks.
func (cq *ChunkQuery) All(ctx context.Context) ([]*Chunk, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Chunk, *ChunkQuery]()
	return withInterceptors[[]*Chunk](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *ChunkQuery) AllX(ctx context.Context) []*Chunk {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Chunk IDs.
func (cq *ChunkQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(chunk.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *ChunkQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *ChunkQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*ChunkQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *ChunkQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *ChunkQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *ChunkQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChunkQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *ChunkQuery) Clone() *ChunkQuery {
	if cq == nil {
		return nil
	}
	return &ChunkQuery{
		config:        cq.config,
		ctx:           cq.ctx.Clone(),
		order:         append([]chunk.OrderOption{}, cq.order...),
		inters:        append([]Interceptor{}, cq.inters...),
		predicates:    append([]predicate.Chunk{}, cq.predicates...),
		withEmbedding: cq.withEmbedding.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithEmbedding tells the query-builder to eager-load the nodes that are connected to
// the "embedding" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ChunkQuery) WithEmbedding(opts ...func(*EmbeddingQuery)) *ChunkQuery {
	query := (&EmbeddingClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withEmbedding = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Path string `json:"path,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Chunk.Query().
//		GroupBy(chunk.FieldPath).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *ChunkQuery) GroupBy(field string, fields ...string) *ChunkGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChunkGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = chunk.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Path string `json:"path,omitempty"`
//	}
//
//	client.Chunk.Query().
//		Select(chunk.FieldPath).
//		Scan(ctx, &v)
func (cq *ChunkQuery) Select(fields ...string) *ChunkSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &ChunkSelect{ChunkQuery: cq}
	sbuild.label = chunk.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChunkSelect configured with the given aggregations.
func (cq *ChunkQuery) Aggregate(fns ...AggregateFunc) *ChunkSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *ChunkQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !chunk.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *ChunkQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Chunk, error) {
	var (
		nodes       = []*Chunk{}
		_spec       = cq.querySpec()
		loadedTypes = [1]bool{
			cq.withEmbedding != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Chunk).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Chunk{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withEmbedding; query != nil {
		if err := cq.loadEmbedding(ctx, query, nodes, nil,
			func(n *Chunk, e *Embedding) { n.Edges.Embedding = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *ChunkQuery) loadEmbedding(ctx context.Context, query *EmbeddingQuery, nodes []*Chunk, init func(*Chunk), assign func(*Chunk, *Embedding)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Chunk)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Embedding(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(chunk.EmbeddingColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.chunk_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "chunk_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "chunk_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *ChunkQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *ChunkQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chunk.Table, chunk.Columns, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chunk.FieldID)
		for i := range fields {
			if fields[i] != chunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *ChunkQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(chunk.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = chunk.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChunkGroupBy is the group-by builder for Chunk entities.
type ChunkGroupBy struct {
	selector
	build *ChunkQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *ChunkGroupBy) Aggregate(fns ...AggregateFunc) *ChunkGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *ChunkGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChunkQuery, *ChunkGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *ChunkGroupBy) sqlScan(ctx context.Context, root *ChunkQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChunkSelect is the builder for selecting fields of Chunk entities.
type ChunkSelect struct {
	*ChunkQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *ChunkSelect) Aggregate(fns ...AggregateFunc) *ChunkSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *ChunkSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChunkQuery, *ChunkSelect](ctx, cs.ChunkQuery, cs, cs.inters, v)
}

func (cs *ChunkSelect) sqlScan(ctx context.Context, root *ChunkQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
