// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TaiwoDevOps/jira-rag/ent/embedding"
	"github.com/TaiwoDevOps/jira-rag/ent/predicate"
)

// EmbeddingDelete is the builder for deleting a Embedding entity.
type EmbeddingDelete struct {
	config
	hooks    []Hook
	mutation *EmbeddingMutation
}

// Where appends a list predicates to the EmbeddingDelete builder.
func (ed *EmbeddingDelete) Where(ps ...predicate.Embedding) *EmbeddingDelete {
	ed.mutation.Where(ps...)
	return ed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ed *EmbeddingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ed.sqlExec, ed.mutation, ed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ed *EmbeddingDelete) ExecX(ctx context.Context) int {
	n, err := ed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ed *EmbeddingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(embedding.Table, sqlgraph.NewFieldSpec(embedding.FieldID, field.TypeInt))
	if ps := ed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ed.mutation.done = true
	return affected, err
}

// EmbeddingDeleteOne is the builder for deleting a single Embedding entity.
type EmbeddingDeleteOne struct {
	ed *EmbeddingDelete
}

// Where appends a list predicates to the EmbeddingDelete builder.
func (edo *EmbeddingDeleteOne) Where(ps ...predicate.Embedding) *EmbeddingDeleteOne {
	edo.ed.mutation.Where(ps...)
	return edo
}

// Exec executes the deletion query.
func (edo *EmbeddingDeleteOne) Exec(ctx context.Context) error {
	n, err := edo.ed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{embedding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (edo *EmbeddingDeleteOne) ExecX(ctx context.Context) {
	if err := edo.Exec(ctx); err != nil {
		panic(err)
	}
}
