// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TaiwoDevOps/jira-rag/ent/chunk"
	"github.com/TaiwoDevOps/jira-rag/ent/embedding"
	"github.com/TaiwoDevOps/jira-rag/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// EmbeddingUpdate is the builder for updating Embedding entities.
type EmbeddingUpdate struct {
	config
	hooks    []Hook
	mutation *EmbeddingMutation
}

// Where appends a list predicates to the EmbeddingUpdate builder.
func (eu *EmbeddingUpdate) Where(ps ...predicate.Embedding) *EmbeddingUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetEmbedding sets the "embedding" field.
func (eu *EmbeddingUpdate) SetEmbedding(pg pgvector.Vector) *EmbeddingUpdate {
	eu.mutation.SetEmbedding(pg)
	return eu
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (eu *EmbeddingUpdate) SetNillableEmbedding(pg *pgvector.Vector) *EmbeddingUpdate {
	if pg != nil {
		eu.SetEmbedding(*pg)
	}
	return eu
}

// SetChunkID sets the "chunk" edge to the Chunk entity by ID.
func (eu *EmbeddingUpdate) SetChunkID(id int) *EmbeddingUpdate {
	eu.mutation.SetChunkID(id)
	return eu
}

// SetChunk sets the "chunk" edge to the Chunk entity.
func (eu *EmbeddingUpdate) SetChunk(c *Chunk) *EmbeddingUpdate {
	return eu.SetChunkID(c.ID)
}

// Mutation returns the EmbeddingMutation object of the builder.
func (eu *EmbeddingUpdate) Mutation() *EmbeddingMutation {
	return eu.mutation
}

// ClearChunk clears the "chunk" edge to the Chunk entity.
func (eu *EmbeddingUpdate) ClearChunk() *EmbeddingUpdate {
	eu.mutation.ClearChunk()
	return eu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EmbeddingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EmbeddingUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EmbeddingUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EmbeddingUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EmbeddingUpdate) check() error {
	if eu.mutation.ChunkCleared() && len(eu.mutation.ChunkIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Embedding.chunk"`)
	}
	return nil
}

func (eu *EmbeddingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(embedding.Table, embedding.Columns, sqlgraph.NewFieldSpec(embedding.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Embedding(); ok {
		_spec.SetField(embedding.FieldEmbedding, field.TypeOther, value)
	}
	if eu.mutation.ChunkCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   embedding.ChunkTable,
			Columns: []string{embedding.ChunkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.ChunkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   embedding.ChunkTable,
			Columns: []string{embedding.ChunkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{embedding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EmbeddingUpdateOne is the builder for updating a single Embedding entity.
type EmbeddingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmbeddingMutation
}

// SetEmbedding sets the "embedding" field.
func (euo *EmbeddingUpdateOne) SetEmbedding(pg pgvector.Vector) *EmbeddingUpdateOne {
	euo.mutation.SetEmbedding(pg)
	return euo
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (euo *EmbeddingUpdateOne) SetNillableEmbedding(pg *pgvector.Vector) *EmbeddingUpdateOne {
	if pg != nil {
		euo.SetEmbedding(*pg)
	}
	return euo
}

// SetChunkID sets the "chunk" edge to the Chunk entity by ID.
func (euo *EmbeddingUpdateOne) SetChunkID(id int) *EmbeddingUpdateOne {
	euo.mutation.SetChunkID(id)
	return euo
}

// SetChunk sets the "chunk" edge to the Chunk entity.
func (euo *EmbeddingUpdateOne) SetChunk(c *Chunk) *EmbeddingUpdateOne {
	return euo.SetChunkID(c.ID)
}

// Mutation returns the EmbeddingMutation object of the builder.
func (euo *EmbeddingUpdateOne) Mutation() *EmbeddingMutation {
	return euo.mutation
}

// ClearChunk clears the "chunk" edge to the Chunk entity.
func (euo *EmbeddingUpdateOne) ClearChunk() *EmbeddingUpdateOne {
	euo.mutation.ClearChunk()
	return euo
}

// Where appends a list predicates to the EmbeddingUpdate builder.
func (euo *EmbeddingUpdateOne) Where(ps ...predicate.Embedding) *EmbeddingUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EmbeddingUpdateOne) Select(field string, fields ...string) *EmbeddingUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Embedding entity.
func (euo *EmbeddingUpdateOne) Save(ctx context.Context) (*Embedding, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EmbeddingUpdateOne) SaveX(ctx context.Context) *Embedding {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EmbeddingUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EmbeddingUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EmbeddingUpdateOne) check() error {
	if euo.mutation.ChunkCleared() && len(euo.mutation.ChunkIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Embedding.chunk"`)
	}
	return nil
}

func (euo *EmbeddingUpdateOne) sqlSave(ctx context.Context) (_node *Embedding, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(embedding.Table, embedding.Columns, sqlgraph.NewFieldSpec(embedding.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Embedding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, embedding.FieldID)
		for _, f := range fields {
			if !embedding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != embedding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.Embedding(); ok {
		_spec.SetField(embedding.FieldEmbedding, field.TypeOther, value)
	}
	if euo.mutation.ChunkCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   embedding.ChunkTable,
			Columns: []string{embedding.ChunkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.ChunkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   embedding.ChunkTable,
			Columns: []string{embedding.ChunkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Embedding{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{embedding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
