// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/TaiwoDevOps/jira-rag/ent/chunk"
	"github.com/TaiwoDevOps/jira-rag/ent/embedding"
	pgvector "github.com/pgvector/pgvector-go"
)

// Embedding is the model entity for the Embedding schema.
type Embedding struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Embedding holds the value of the "embedding" field.
	Embedding pgvector.Vector `json:"embedding,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmbeddingQuery when eager-loading is set.
	Edges        EmbeddingEdges `json:"edges"`
	chunk_id     *int
	selectValues sql.SelectValues
}

// EmbeddingEdges holds the relations/edges for other nodes in the graph.
type EmbeddingEdges struct {
	// Chunk holds the value of the chunk edge.
	Chunk *Chunk `json:"chunk,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ChunkOrErr returns the Chunk value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmbeddingEdges) ChunkOrErr() (*Chunk, error) {
	if e.Chunk != nil {
		return e.Chunk, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chunk.Label}
	}
	return nil, &NotLoadedError{edge: "chunk"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Embedding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case embedding.FieldEmbedding:
			values[i] = new(pgvector.Vector)
		case embedding.FieldID:
			values[i] = new(sql.NullInt64)
		case embedding.ForeignKeys[0]: // chunk_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Embedding fields.
func (e *Embedding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case embedding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			e.ID = int(value.Int64)
		case embedding.FieldEmbedding:
			if value, ok := values[i].(*pgvector.Vector); !ok {
				return fmt.Errorf("unexpected type %T for field embedding", values[i])
			} else if value != nil {
				e.Embedding = *value
			}
		case embedding.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field chunk_id", value)
			} else if value.Valid {
				e.chunk_id = new(int)
				*e.chunk_id = int(value.Int64)
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Embedding.
// This includes values selected through modifiers, order, etc.
func (e *Embedding) Value(name string) (ent.Value, error) {
	return e.selectValues.Get(name)
}

// QueryChunk queries the "chunk" edge of the Embedding entity.
func (e *Embedding) QueryChunk() *ChunkQuery {
	return NewEmbeddingClient(e.config).QueryChunk(e)
}

// Update returns a builder for updating this Embedding.
// Note that you need to call Embedding.Unwrap() before calling this method if this Embedding
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Embedding) Update() *EmbeddingUpdateOne {
	return NewEmbeddingClient(e.config).UpdateOne(e)
}

// Unwrap unwraps the Embedding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Embedding) Unwrap() *Embedding {
	_tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Embedding is not a transactional entity")
	}
	e.config.driver = _tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Embedding) String() string {
	var builder strings.Builder
	builder.WriteString("Embedding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", e.ID))
	builder.WriteString("embedding=")
	builder.WriteString(fmt.Sprintf("%v", e.Embedding))
	builder.WriteByte(')')
	return builder.String()
}

// Embeddings is a parsable slice of Embedding.
type Embeddings []*Embedding
